// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB7QHQZZjtSJFlNJyviBNxL_5n2TLedFZs',
    appId: '1:612038671774:web:843feb553c057140402a8f',
    messagingSenderId: '612038671774',
    projectId: 'instagram-clone-5a0b2',
    authDomain: 'instagram-clone-5a0b2.firebaseapp.com',
    storageBucket: 'instagram-clone-5a0b2.appspot.com',
    measurementId: 'G-SEN4NF4N62',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAiU6y8FPYJxpknn4DljAzChBP0UVldzuk',
    appId: '1:612038671774:android:1a3c14a33e356ac3402a8f',
    messagingSenderId: '612038671774',
    projectId: 'instagram-clone-5a0b2',
    storageBucket: 'instagram-clone-5a0b2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDWqRZAtsGgtvJ6PRK8F9KUfHCD4VaK6wQ',
    appId: '1:612038671774:ios:837a583d0dbd9ba2402a8f',
    messagingSenderId: '612038671774',
    projectId: 'instagram-clone-5a0b2',
    storageBucket: 'instagram-clone-5a0b2.appspot.com',
    iosClientId: '612038671774-kklai0801dqgqot7sl1qel2m7ktgkfi3.apps.googleusercontent.com',
    iosBundleId: 'com.example.instaClone',
  );
}
